package com.example.adrian.pawsible;

/**
 * Created by Adrian on 24/3/2018.
 */
public enum Breed{
    GOLDEN_RETRIEVER,
    LABRADOR,
    SINGAPORE_SPECIAL,
    MALTIPOO,
    BISCHON,
    GOLDENDOODLE,
    LABRADOODLE,
    PUG,
    SHIHTZU,
    BASSETHOUND,
    VIZLA,
    SPITZ,
    SHIBAINU,
    BORDER_COLLIE,
    SHETLAND_SHEEPDOG,
    SCOTTISH_TERRIER,
    SCHNAUZER,
    JACK_RUSSELL,
    DACHSHUND,
    POODLE,
    COCKER_SPANIEL,
    BULLDOG,
    CHOW_CHOW,
    YORKSHIRE_TERRIER,
    MALTESE,
    BEAGLE,
    POMERANIAN,
    OTHERS,
}

