package com.example.adrian.pawsible;

/**
 * Created by Adrian on 24/3/2018.
 */
public enum Breed{
    GOLDENRETRIEVER,
    LABRADOR,
    SINGAPORESPECIAL,
    MALTIPOO,
    BISCHON,
    GOLDENDOODLE,
    LABRADOODLE,
    PUG,
    SHIHTZU,
    BASSETHOUND,
    VIZLA,
    SPITZ,
    SHIBAINU,
    BORDERCOLLIE,
    SHETLANDSHEEPDOG,
    SCOTTISHTERRIER,
    SCHNAUZER,
    JACKRUSSELL,
    DACHSHUND,
    POODLE,
    COCKERSPANIEL,
    BULLDOG,
    CHOWCHOW,
    YORKSHIRETERRIER,
    MALTESE,
    BEAGLE,
    POMERANIAN,
    OTHERS,
}

